# permissions for end users to view placementapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: placementapi-viewer-role
rules:
- apiGroups:
  - placement.openstack.org
  resources:
  - placementapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - placement.openstack.org
  resources:
  - placementapis/status
  verbs:
  - get
