---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - placement.openstack.org
  resources:
  - placementapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - placement.openstack.org
  resources:
  - placementapis/finalizers
  verbs:
  - update
- apiGroups:
  - placement.openstack.org
  resources:
  - placementapis/status
  verbs:
  - get
  - patch
  - update
